import { useEffect, useState } from 'react'
import css from './AnalysisResultCard.module.css'

/** One tabular section prepared by a GIS skill for in-chat display. */
type AnalysisTable = {
  id: string
  title: string
  columns: string[]
  rows: string[][]
}

/** Small, local JSON document produced alongside the office deliverables. */
type AnalysisView = {
  schema_version: number
  title: string
  generated_at: string
  tables: AnalysisTable[]
}

type DesktopBridge = {
  core?: {
    invoke?: (command: string, argumentsValue?: unknown) => Promise<unknown>
  }
}

type DesktopInternals = {
  invoke?: (command: string, argumentsValue?: unknown) => Promise<unknown>
}

const desktopWindow = window as Window & {
  __TAURI__?: DesktopBridge
  __TAURI_INTERNALS__?: DesktopInternals
}

function isAnalysisView(value: unknown): value is AnalysisView {
  if (value === null || typeof value !== 'object') return false
  const record = value as Partial<AnalysisView>
  return typeof record.title === 'string' && Array.isArray(record.tables)
}

/**
 * Read and render the compact local analysis view generated by a GIS skill.
 * @param path - Produced analysis-view JSON path.
 * @param openFile - Host file opener for the formal office deliverables.
 * @param excelPath - Generated analysis workbook path.
 * @param wordPath - Generated professional report path.
 * @returns An interactive result card, or nothing outside the desktop shell.
 */
export function AnalysisResultCard({
  path, openFile, excelPath, wordPath,
}: {
  path: string
  openFile: (path: string) => void
  excelPath: string | undefined
  wordPath: string | undefined
}) {
  const [view, setView] = useState<AnalysisView | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [expanded, setExpanded] = useState(false)

  useEffect(() => {
    const invoke = desktopWindow.__TAURI__?.core?.invoke ?? desktopWindow.__TAURI_INTERNALS__?.invoke
    if (invoke === undefined) return
    let active = true
    void invoke('read_analysis_view', { path })
      .then((value) => {
        if (!active || typeof value !== 'string') return
        const parsed: unknown = JSON.parse(value)
        if (!isAnalysisView(parsed)) return
        setView(parsed)
        setSelectedId(parsed.tables[0]?.id ?? null)
      })
      .catch(() => undefined)
    return () => { active = false }
  }, [path])

  if (view === null || view.tables.length === 0) return null
  const selected = view.tables.find(table => table.id === selectedId) ?? view.tables.at(0)
  if (selected === undefined) return null
  const rows = expanded ? selected.rows : selected.rows.slice(0, 8)
  return (
    <section className={css.root} aria-label={`${view.title}结果表格`}>
      <div className={css.heading}>
        <div>
          <div className={css.kicker}>分析结果</div>
          <h3>{view.title}</h3>
        </div>
        <div className={css.actions}>
          {excelPath !== undefined && (
            <button type="button" onClick={() => { openFile(excelPath) }}>打开 Excel</button>
          )}
          {wordPath !== undefined && (
            <button type="button" onClick={() => { openFile(wordPath) }}>打开 Word</button>
          )}
        </div>
      </div>
      <div className={css.tabs} role="tablist" aria-label="分析数据分类">
        {view.tables.map(table => (
          <button
            key={table.id}
            type="button"
            role="tab"
            aria-selected={selected.id === table.id}
            className={selected.id === table.id ? css.tabActive : css.tab}
            onClick={() => { setSelectedId(table.id); setExpanded(false) }}
          >
            {table.title}
          </button>
        ))}
      </div>
      <div className={css.tableWrap}>
        <table>
          <thead>
            <tr>{selected.columns.map(column => <th key={column}>{column}</th>)}</tr>
          </thead>
          <tbody>
            {rows.map((row, index) => (
              <tr key={`${selected.id}-${index}`}>
                {selected.columns.map((column, columnIndex) => (
                  <td key={column}>{row[columnIndex] ?? '—'}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {selected.rows.length > 8 && (
        <button type="button" className={css.expand} onClick={() => { setExpanded(value => !value) }}>
          {expanded ? '收起明细' : `查看全部 ${selected.rows.length} 条`}
        </button>
      )}
    </section>
  )
}
