/** Generated from the checked-in official skill manifests. */
export const OFFICIAL_SKILLS = [
  {
    'id': 'gis-geology-analysis',
    'slug': 'market-gis-geology-analysis',
    'name': '地质条件分析',
    'category': '空间制图',
    'tags': [
      '官方',
      '推荐',
    ],
    'summary': '识别 GeoJSON、Shape 文件夹或 Shape ZIP 的项目范围，调用 GIS_Service 分析地质环境与地质灾害隐患分区。',
    'description': '读取工作区中的 GeoJSON、完整 Shape 文件夹、.shp 文件或 Shape ZIP，自动提取面范围和坐标系信息，调用地质条件分析服务并交付原始 JSON、Excel 明细表和详尽 Word 分析报告。',
    'installs': '0',
    'accent': '#a855f7',
    'icon': '地',
    'version': '1.4.6',
    'author': 'ZJUGIS GIS 服务',
    'featured': true,
    'params': [
      {
        'name': 'inputPath',
        'type': 'file',
        'required': true,
        'description': 'Polygon/MultiPolygon GeoJSON、.shp、包含完整 Shape 文件的 ZIP 或文件夹',
      },
      {
        'name': 'YfxFieldName',
        'type': 'string',
        'required': false,
        'description': '分区名称字段',
        'defaultValue': '分区名称',
      },
    ],
    'installable': true,
  },
  {
    'id': 'gis-land-use-plan-review',
    'slug': 'market-gis-land-use-plan-review',
    'name': '土地利用规划审查',
    'category': '空间制图',
    'tags': [
      '官方',
      '推荐',
    ],
    'summary': '识别 GeoJSON、Shape 文件夹或 Shape ZIP 的项目范围，调用 GIS_Service 开展土地利用规划符合性审查。',
    'description': '读取工作区中的 GeoJSON、完整 Shape 文件夹、.shp 文件或 Shape ZIP，自动提取面范围和坐标系信息，调用规划审查接口并交付原始 JSON、Excel 明细表和详尽 Word 分析报告。当前服务示例审查类别 Blxsw 默认为 4。',
    'installs': '0',
    'accent': '#2563eb',
    'icon': '审',
    'version': '1.4.6',
    'author': 'ZJUGIS GIS 服务',
    'featured': true,
    'params': [
      {
        'name': 'inputPath',
        'type': 'file',
        'required': true,
        'description': 'Polygon/MultiPolygon GeoJSON、.shp、包含完整 Shape 文件的 ZIP 或文件夹',
      },
      {
        'name': 'Blxsw',
        'type': 'number',
        'required': false,
        'description': '服务审查类别编码',
        'defaultValue': '4',
      },
    ],
    'installable': true,
  },
  {
    'id': 'gis-third-survey-analysis',
    'slug': 'market-gis-third-survey-analysis',
    'name': '三调土地利用现状分析',
    'category': '空间制图',
    'tags': [
      '官方',
      '推荐',
    ],
    'summary': '识别 GeoJSON、Shape 文件夹或 Shape ZIP 的项目范围，调用 GIS_Service 开展三调土地利用现状与图斑分析。',
    'description': '读取工作区中的 GeoJSON、完整 Shape 文件夹、.shp 文件或 Shape ZIP，自动提取面范围和坐标系信息，调用 SanDXzAnalysis 并交付原始 JSON、Excel 明细表和详尽 Word 分析报告。',
    'installs': '0',
    'accent': '#059669',
    'icon': '三',
    'version': '1.4.6',
    'author': 'ZJUGIS GIS 服务',
    'featured': true,
    'params': [
      {
        'name': 'inputPath',
        'type': 'file',
        'required': true,
        'description': 'Polygon/MultiPolygon GeoJSON、.shp、包含完整 Shape 文件的 ZIP 或文件夹',
      },
      {
        'name': 'Xznf',
        'type': 'number',
        'required': false,
        'description': '三调现状年度',
        'defaultValue': '2024',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-batch-rename',
    'slug': 'office-batch-rename',
    'name': '文件批量重命名',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '按项目名、日期、序号等规则批量重命名文件，执行前先生成预览清单。',
    'description': '按项目名、日期、序号等规则批量重命名文件，执行前先生成预览清单。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#0f766e',
    'icon': '名',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '需要重命名的文件',
      },
      {
        'name': 'template',
        'type': 'string',
        'required': true,
        'description': '命名模板，支持 {project} {date} {index} {name} {ext}',
      },
      {
        'name': 'project',
        'type': 'string',
        'required': false,
        'description': '项目名',
      },
      {
        'name': 'startIndex',
        'type': 'number',
        'required': false,
        'description': '起始序号',
        'defaultValue': '1',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-document-compare',
    'slug': 'office-document-compare',
    'name': '文档对比助手',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '对比两份 Word、PDF 或文本文件，整理新增、删除和修改内容。',
    'description': '对比两份 Word、PDF 或文本文件，整理新增、删除和修改内容。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#db2777',
    'icon': '比',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'originalPath',
        'type': 'file',
        'required': true,
        'description': '原始版本',
      },
      {
        'name': 'revisedPath',
        'type': 'file',
        'required': true,
        'description': '新版本',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-document-summary',
    'slug': 'office-document-summary',
    'name': '文档摘要与要点提取',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '读取 Word、PDF、Excel 和文本材料，提炼重点、风险、时间节点和待办事项。',
    'description': '读取 Word、PDF、Excel 和文本材料，提炼重点、风险、时间节点和待办事项。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#4f46e5',
    'icon': '摘',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '一个或多个 Word、PDF、Excel 或文本文件',
      },
      {
        'name': 'focus',
        'type': 'string',
        'required': false,
        'description': '可选关注重点',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-excel-data-cleaner',
    'slug': 'office-excel-data-cleaner',
    'name': 'Excel 数据处理',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '清理 Excel 台账，完成去重、筛选、文本规范化、格式统一和基础统计。',
    'description': '清理 Excel 台账，完成去重、筛选、文本规范化、格式统一和基础统计。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#16a34a',
    'icon': '表',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPath',
        'type': 'file',
        'required': true,
        'description': 'Excel 工作簿',
      },
      {
        'name': 'sheet',
        'type': 'string',
        'required': false,
        'description': '工作表名称；留空使用首个工作表',
      },
      {
        'name': 'dedupeColumns',
        'type': 'string',
        'required': false,
        'description': '去重列名，多个用英文逗号分隔',
      },
      {
        'name': 'filter',
        'type': 'string',
        'required': false,
        'description': '筛选条件，例如 状态=有效',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-image-optimizer',
    'slug': 'office-image-optimizer',
    'name': '图片压缩与格式转换',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '批量压缩图片、按最大尺寸缩放，并转换为 JPG、PNG 或 WebP。',
    'description': '批量压缩图片、按最大尺寸缩放，并转换为 JPG、PNG 或 WebP。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#ca8a04',
    'icon': '压',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '一个或多个图片',
      },
      {
        'name': 'format',
        'type': 'select',
        'required': true,
        'description': '输出格式',
        'options': [
          'jpg',
          'png',
          'webp',
        ],
        'defaultValue': 'jpg',
      },
      {
        'name': 'quality',
        'type': 'number',
        'required': false,
        'description': '质量 1–100',
        'defaultValue': '85',
      },
      {
        'name': 'maxWidth',
        'type': 'number',
        'required': false,
        'description': '最大宽度；0 表示不限制',
        'defaultValue': '0',
      },
      {
        'name': 'maxHeight',
        'type': 'number',
        'required': false,
        'description': '最大高度；0 表示不限制',
        'defaultValue': '0',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-images-to-pdf',
    'slug': 'office-images-to-pdf',
    'name': '图片转 PDF',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '将多张图片按指定顺序排版为一个 PDF，支持常见纸张、方向和页边距。',
    'description': '将多张图片按指定顺序排版为一个 PDF，支持常见纸张、方向和页边距。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#ea580c',
    'icon': '册',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '按页面顺序提供图片',
      },
      {
        'name': 'pageSize',
        'type': 'select',
        'required': true,
        'description': '纸张',
        'options': [
          'A4',
          'A3',
          'Letter',
          'original',
        ],
        'defaultValue': 'A4',
      },
      {
        'name': 'orientation',
        'type': 'select',
        'required': true,
        'description': '方向',
        'options': [
          'auto',
          'portrait',
          'landscape',
        ],
        'defaultValue': 'auto',
      },
      {
        'name': 'marginMm',
        'type': 'number',
        'required': false,
        'description': '页边距（毫米）',
        'defaultValue': '10',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-meeting-minutes',
    'slug': 'office-meeting-minutes',
    'name': '会议纪要',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '将会议语音转为文字，并结合会议材料生成结构化 Markdown 和 Word 会议纪要。',
    'description': '将会议语音转为文字，并结合会议材料生成结构化 Markdown 和 Word 会议纪要。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#9333ea',
    'icon': '会',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'materials',
        'type': 'files',
        'required': true,
        'description': '会议材料或已有转写稿',
      },
      {
        'name': 'audioPath',
        'type': 'file',
        'required': false,
        'description': '可选语音文件；需先配置转写接口',
      },
      {
        'name': 'meetingTitle',
        'type': 'string',
        'required': false,
        'description': '会议名称',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-pdf-organizer',
    'slug': 'office-pdf-organizer',
    'name': 'PDF 合并拆分',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '将多个 PDF 按指定顺序合并，或按页码范围拆分和提取页面。',
    'description': '将多个 PDF 按指定顺序合并，或按页码范围拆分和提取页面。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#7c3aed',
    'icon': '合',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'operation',
        'type': 'select',
        'required': true,
        'description': '处理方式',
        'options': [
          'merge',
          'split',
        ],
        'defaultValue': 'merge',
      },
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '合并时按顺序提供 PDF；拆分时提供一个 PDF',
      },
      {
        'name': 'ranges',
        'type': 'string',
        'required': false,
        'description': '拆分页码，例如 1-3,5,8-10',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-pdf-to-images',
    'slug': 'office-pdf-to-images',
    'name': 'PDF 转图片',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '将 PDF 每一页批量转换为 PNG 或 JPG，支持清晰度和页码范围控制。',
    'description': '将 PDF 每一页批量转换为 PNG 或 JPG，支持清晰度和页码范围控制。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#0891b2',
    'icon': '图',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPath',
        'type': 'file',
        'required': true,
        'description': 'PDF 文件',
      },
      {
        'name': 'format',
        'type': 'select',
        'required': true,
        'description': '图片格式',
        'options': [
          'png',
          'jpg',
        ],
        'defaultValue': 'png',
      },
      {
        'name': 'dpi',
        'type': 'number',
        'required': false,
        'description': '清晰度 DPI',
        'defaultValue': '144',
      },
      {
        'name': 'pages',
        'type': 'string',
        'required': false,
        'description': '可选页码范围，例如 1-3,5',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
  {
    'id': 'office-word-to-pdf',
    'slug': 'office-word-to-pdf',
    'name': 'Word 转 PDF',
    'category': '办公工具',
    'tags': [
      '官方',
      '办公',
      '演示',
    ],
    'summary': '将一个或多个 Word 文档转换为便于打印、发送和归档的 PDF，并保持原文件不变。',
    'description': '将一个或多个 Word 文档转换为便于打印、发送和归档的 PDF，并保持原文件不变。 包含可直接运行的本地处理脚本、依赖说明、错误处理和统一中文交付规范。',
    'installs': '0',
    'accent': '#2563eb',
    'icon': 'W',
    'version': '1.0.0',
    'author': '万维Buddy 办公工具',
    'featured': true,
    'params': [
      {
        'name': 'inputPaths',
        'type': 'files',
        'required': true,
        'description': '一个或多个 .doc、.docx、.docm 文件',
      },
      {
        'name': 'outputDirectory',
        'type': 'directory',
        'required': false,
        'description': '输出目录；留空时在输入文件旁创建独立目录',
      },
    ],
    'installable': true,
  },
] as const
